[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-dark_klemen
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-dark_klemen
GtkTheme=oomox-dark_klemen
IconTheme=oomox-dark_klemen
MetacityTheme=oomox-dark_klemen
