#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
OS=`uname -s`

[ -f $HOME/.xprofile ] && . $HOME/.xprofile
[ -f $HOME/.profile ] && . $HOME/.profile
[ -f $HOME/.Xresources ] && xrdb -merge $HOME/.Xresources

i3
