#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
OS=`uname -s`

[ -f ~/.xprofile ] && source ~/.xprofile
[ -f $HOME/.profile ] && source $HOME/.profile
[ -f $HOME/.Xresources ] && xrdb -merge $HOME/.Xresources

i3
